### ISSUE TITLE
Not working on Moto G

### ISSUE THREAD

**Issue by bg17aw** [AbinashBishoyi/WhatsApp-Key-DB-Extractor#5]
I tried on two different Moto G (xt1032 not rooted and xt1033 rooted).

On both I get the same error after pressing on Backup my data:

<code>
Backing up WhatsApp
Now unlock your device and confirm the backup operation.

Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: ""
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:203)
        at org.nick.abe.Main.main(Main.java:35)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:67)
        ... 1 more
bin\tar: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar: Error is not recoverable: exiting now
bin\tar: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar: Error is not recoverable: exiting now
bin\tar: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar: Error is not recoverable: exiting now

Extracting whatsapp.key ...
File not found - key
0 File(s) copied

Extracting msgstore.db ...
The system cannot find the path specified.

Extracting wa.db ...
The system cannot find the path specified.

Pushing cipher key to: /sdcard/WhatsApp/Databases/.nomedia
cannot stat 'tmp\apps\com.whatsapp\f\key': No such file or directory

Cleaning up temporary files ...

Deleted file - c:\Users\x201\Downloads\WhatsApp-Key-DB-Extractor-master\tmp\whatsapp.ab
Could Not Find c:\Users\x201\Downloads\WhatsApp-Key-DB-Extractor-master\tmp\whatsapp.tar
The system cannot find the file specified.

Done
</code>

**Comment by darioadrianz** [comment]
It happened the same on my moto g 2nd gen, the only thing different is that I couldn't tap the 'back up my data' button, it wasn't even highlighted.

**Comment by kaushalshah** [comment]
Same For my asus Zenfone 2
